Repository BedrockStreaming/forms, pull requests merged in 2022-03, with the labels that each got.

#65 docs(project): update the documentation
  .github/CONTRIBUTING.md
  README.md
Labels: documentation, Tech review needed

#76 build(deps): fix vulnerabilities
  package.json
  yarn.lock
Labels: dependencies, priority:high

#79 ci(nx-cloud): optin on nx cloud computing
  nx.json
  package.json
  yarn.lock
Labels: 📦 dependencies

#80 ci(git): prevent slash and uppercase in branch names
  .husky/pre-push
  .validate-branch-namerc.js
  package.json
  yarn.lock
Labels: ⚙ CI/CD
